// ============================================================
// base_cards.ts  –  基本セット（無印）建物カード定義
// ============================================================
import type { CardDef } from './types';

export const BASE_CARD_DEFS: CardDef[] = [
    // ===== コスト 1 =====
    {
        id: 'farm',
        name: '農場',
        cost: 1,
        vp: 6,
        copies: 8,
        tags: ['farm'],
        unsellable: false,
        consumeOnUse: false,
        effectText: '消費財を2枚引く',
        image: '/cards/progress/prog_farm.png',
    },
    {
        id: 'slash_burn',
        name: '焼畑',
        cost: 1,
        vp: 0,
        copies: 2,
        tags: ['farm'],
        unsellable: true,
        consumeOnUse: true,
        effectText: '消費財を5枚引く。使用後捨て札。',
        image: '/cards/progress/prog_slash_burn.png',
    },
    {
        id: 'coffee_shop',
        name: '珈琲店',
        cost: 1,
        vp: 8,
        copies: 2,
        tags: [],
        unsellable: false,
        consumeOnUse: false,
        effectText: '家計から$5を得る',
        image: '/cards/progress/prog_coffee_shop.png',
    },
    {
        id: 'design_office',
        name: '設計事務所',
        cost: 1,
        vp: 8,
        copies: 4,
        tags: [],
        unsellable: false,
        consumeOnUse: false,
        effectText: '山札から5枚公開し、1枚を手札に加え残りを捨てる',
        image: '/cards/progress/prog_design_office.png',
    },

    // ===== コスト 2 =====
    {
        id: 'factory',
        name: '工場',
        cost: 2,
        vp: 12,
        copies: 8,
        tags: ['factory'],
        unsellable: false,
        consumeOnUse: false,
        effectText: '手札2枚捨てて、4枚引く',
        image: '/cards/progress/prog_factory.png',
    },
    {
        id: 'construction_co',
        name: '建設会社',
        cost: 2,
        vp: 10,
        copies: 4,
        tags: [],
        unsellable: false,
        consumeOnUse: false,
        effectText: '建物を1つ作る（コスト-1）',
        image: '/cards/progress/prog_construction_co.png',
    },
    {
        id: 'warehouse',
        name: '倉庫',
        cost: 2,
        vp: 10,
        copies: 3,
        tags: [],
        unsellable: true,
        consumeOnUse: false,
        effectText: '手札上限+4',
        image: '/cards/progress/prog_warehouse.png',
    },
    {
        id: 'law_office',
        name: '法律事務所',
        cost: 2,
        vp: 8,
        copies: 1,
        tags: [],
        unsellable: true,
        consumeOnUse: false,
        effectText: '終了時、負債トークン5枚までを免除',
        image: '/cards/progress/prog_law_office.png',
    },
    {
        id: 'orchard',
        name: '果樹園',
        cost: 2,
        vp: 10,
        copies: 3,
        tags: ['farm'],
        unsellable: false,
        consumeOnUse: false,
        effectText: '手札が4枚になるまで消費財を引く',
        image: '/cards/progress/prog_orchard.png',
    },
    {
        id: 'company_housing',
        name: '社宅',
        cost: 2,
        vp: 8,
        copies: 2,
        tags: [],
        unsellable: true,
        consumeOnUse: false,
        effectText: '労働者上限+1',
        image: '/cards/progress/prog_company_housing.png',
    },

    // ===== コスト 3 =====
    {
        id: 'real_estate',
        name: '不動産屋',
        cost: 3,
        vp: 10,
        copies: 2,
        tags: [],
        unsellable: true,
        consumeOnUse: false,
        effectText: '終了時、所有建物1つにつき+3VP',
        image: '/cards/progress/prog_real_estate.png',
    },
    {
        id: 'pioneer',
        name: '開拓民',
        cost: 3,
        vp: 14,
        copies: 2,
        tags: [],
        unsellable: false,
        consumeOnUse: false,
        effectText: '手札にある[※農園]マーク付き建物を1つ無料で建設する',
        image: '/cards/progress/prog_pioneer.png',
    },
    {
        id: 'restaurant',
        name: 'レストラン',
        cost: 3,
        vp: 16,
        copies: 2,
        tags: [],
        unsellable: false,
        consumeOnUse: false,
        effectText: '手札1枚捨てて、家計から$15を得る',
        image: '/cards/progress/prog_restaurant.png',
    },
    {
        id: 'large_farm',
        name: '大農園',
        cost: 3,
        vp: 12,
        copies: 3,
        tags: ['farm'],
        unsellable: false,
        consumeOnUse: false,
        effectText: '消費財を3枚引く',
        image: '/cards/progress/prog_large_farm.png',
    },
    {
        id: 'agri_coop',
        name: '農協',
        cost: 3,
        vp: 12,
        copies: 1,
        tags: [],
        unsellable: true,
        consumeOnUse: false,
        effectText: '終了時、手札の消費財1枚につき+3VP',
        image: '/cards/progress/prog_agri_coop.png',
    },

    // ===== コスト 4 =====
    {
        id: 'general_contractor',
        name: 'ゼネコン',
        cost: 4,
        vp: 18,
        copies: 3,
        tags: [],
        unsellable: false,
        consumeOnUse: false,
        effectText: '建物を1つ作り、その後カードを2枚引く',
        image: '/cards/progress/prog_general_contractor.png',
    },
    {
        id: 'steel_mill',
        name: '製鉄所',
        cost: 4,
        vp: 20,
        copies: 3,
        tags: ['factory'],
        unsellable: false,
        consumeOnUse: false,
        effectText: 'カードを3枚引く',
        image: '/cards/progress/prog_steel_mill.png',
    },
    {
        id: 'mansion',
        name: '邸宅',
        cost: 4,
        vp: 28,
        copies: 1,
        tags: [],
        unsellable: true,
        consumeOnUse: false,
        effectText: '効果なし（VPのみ）',
        image: '/cards/progress/prog_mansion.png',
    },
    {
        id: 'chemical_plant',
        name: '化学工場',
        cost: 4,
        vp: 18,
        copies: 2,
        tags: ['factory'],
        unsellable: false,
        consumeOnUse: false,
        effectText: 'カードを2枚引く（手札0枚なら4枚引く）',
        image: '/cards/progress/prog_chemical_plant.png',
    },
    {
        id: 'labor_union',
        name: '労働組合',
        cost: 4,
        vp: 0,
        copies: 1,
        tags: [],
        unsellable: true,
        consumeOnUse: false,
        effectText: '終了時、労働者1人につき+6VP',
        image: '/cards/progress/prog_labor_union.png',
    },

    // ===== コスト 5 =====
    {
        id: 'auto_factory',
        name: '自動車工場',
        cost: 5,
        vp: 24,
        copies: 3,
        tags: ['factory'],
        unsellable: false,
        consumeOnUse: false,
        effectText: '手札3枚捨てて、7枚引く',
        image: '/cards/progress/prog_auto_factory.png',
    },
    {
        id: 'headquarters',
        name: '本社ビル',
        cost: 5,
        vp: 20,
        copies: 1,
        tags: [],
        unsellable: true,
        consumeOnUse: false,
        effectText: '終了時、所有する[売却不可]マークにつき+6VP',
        image: '/cards/progress/prog_headquarters.png',
    },
    {
        id: 'dual_construction',
        name: '二胡市建設',
        cost: 5,
        vp: 20,
        copies: 2,
        tags: [],
        unsellable: false,
        consumeOnUse: false,
        effectText: '同じコストの建物を2つ同時に作る（コストは1つ分のみ支払う）',
        image: '/cards/progress/prog_dual_construction.png',
    },
    {
        id: 'railroad',
        name: '鉄道',
        cost: 5,
        vp: 18,
        copies: 1,
        tags: [],
        unsellable: true,
        consumeOnUse: false,
        effectText: '終了時、所有する[※工場]マークにつき+8VP',
        image: '/cards/progress/prog_railroad.png',
    },
];
